# Generated by Django 4.2.11 on 2026-05-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='CODIGO', max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, verbose_name='Nombre')),
                ('activo', models.CharField(choices=[('S', 'Activo'), ('N', 'Inactivo')], db_column='ACTIVO', default='S', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'PERMISOS_MODULOS',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(blank=True, db_column='PUEDE_VER', null=True, verbose_name='Ver')),
                ('puede_crear', models.BooleanField(blank=True, db_column='PUEDE_CREAR', null=True, verbose_name='Crear')),
                ('puede_editar', models.BooleanField(blank=True, db_column='PUEDE_EDITAR', null=True, verbose_name='Editar')),
                ('puede_eliminar', models.BooleanField(blank=True, db_column='PUEDE_ELIMINAR', null=True, verbose_name='Eliminar')),
                ('modulo', models.ForeignKey(db_column='ID_MODULO', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='permisos.modulo', verbose_name='Módulo')),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso por Usuario',
                'verbose_name_plural': 'Permisos por Usuario',
                'db_table': 'PERMISOS_USUARIO',
                'ordering': ['usuario__username', 'modulo__nombre'],
                'managed': True,
                'unique_together': {('usuario', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrativo', 'Administrativo'), ('medico', 'Médico'), ('paciente', 'Paciente'), ('auxiliar_medico', 'Auxiliar Médico')], db_column='ROL', max_length=30, verbose_name='Rol')),
                ('puede_ver', models.BooleanField(db_column='PUEDE_VER', default=False, verbose_name='Ver')),
                ('puede_crear', models.BooleanField(db_column='PUEDE_CREAR', default=False, verbose_name='Crear')),
                ('puede_editar', models.BooleanField(db_column='PUEDE_EDITAR', default=False, verbose_name='Editar')),
                ('puede_eliminar', models.BooleanField(db_column='PUEDE_ELIMINAR', default=False, verbose_name='Eliminar')),
                ('modulo', models.ForeignKey(db_column='ID_MODULO', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_rol', to='permisos.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'db_table': 'PERMISOS_ROL',
                'ordering': ['rol', 'modulo__nombre'],
                'managed': True,
                'unique_together': {('rol', 'modulo')},
            },
        ),
    ]
